---
- name: "Destroying Kubenetes Infrastructure"
  hosts: 127.0.0.1
  connection: local
  vars:
    - workflowId: 1010102
    
  tasks:  
  
  - name: Destroy EC2 for K8S
    ansible.builtin.shell: |
      aws cloudformation delete-stack --stack-name "devops-capstone-infra-tjk-{{workflowId}}"
    register: ec2_k8s
    
  - name: Debug Info
    ansible.builtin.debug:
      var: ec2_k8s
