---
- name: "Creating Kubenetes Infrastructure"
  hosts: k8s
  user: ec2-user
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - workflowId: 1010102
    - ansible_ssh_private_key_file: "~/environment/.ssh/udacity.pem"
    
  tasks:  

  - name: Install yum utils
    yum:
      name: yum-utils
      state: latest
        
  - name: Install Docker
    package:
      name: docker
      state: latest
    become: yes

  - name: Add to docker group
    ansible.builtin.shell: |
      usermod -a -G docker ec2-user
    become: yes  

  - name: Start Docker service
    service:
      name: docker
      state: started
      enabled: yes
  
  - name: Install kubectl
    get_url:
      url: https://dl.k8s.io/release/v1.23.1/bin/linux/amd64/kubectl
      dest: /usr/bin/kubectl
      mode: '0755'  
    register: install_kubectl
    
  - name: Debug Info
    ansible.builtin.debug:
      var: install_kubectl


  - name: Install minikube
    get_url:
      url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
      dest: /usr/bin/minikube
      mode: '0755'  
    register: install_minikube
    
  - name: Debug Info
    ansible.builtin.debug:
      var: install_minikube
  
  
  - name: Start minikube
    ansible.builtin.shell: |
      runuser -u ec2-user -- minikube start
    register: start_minikube
    
  - name: Debug Info
    ansible.builtin.debug:
      var: start_minikube
