apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: tjk-devops-cluster
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    minSize: 1
    maxSize: 2    
    desiredCapacity: 1
    volumeSize: 20
    ssh: # use existing EC2 key
      publicKeyName: udacity
