version: 2.1

parameters:

  setup-eks-cluster-infra:
    type: boolean
    default: false

  workflow-id:
    type: string
    default: "${CIRCLE_WORKFLOW_ID:0:7}"

orbs:

  aws-ecr: circleci/aws-ecr@7.3.0
  aws-eks: circleci/aws-eks@2.1.0
  kubernetes: circleci/kubernetes@1.3.0

executors:

  python3:
    docker:
      - image: cimg/python:3.10-browsers

jobs:

  test-cluster:
    executor: python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
      aws-region:
        description: |
          AWS region
        type: string
        default: ""

    steps:

      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          aws-region: << parameters.aws-region >>
          install-kubectl: true

      - run:
          command: |
            kubectl get services
          name: Test cluster 1

workflows:

  setup-eks-cluster-infra:
    when: << pipeline.parameters.setup-eks-cluster-infra >>

    jobs:

      - aws-eks/create-cluster:
          executor: python3
          cluster-name: my-eks-demo
          aws-region: $AWS_DEFAULT_REGION
          show-eksctl-command: true

      - test-cluster:
          cluster-name: my-eks-demo
          aws-region: $AWS_DEFAULT_REGION
          requires:
            - aws-eks/create-cluster
